<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' and ' => ' եւ ',
    '(not set)' => '(նշված չէ)',
    'An internal server error occurred.' => 'Ներքին սերվերի սխալ է տեղի ունեցել:',
    'Delete' => 'Ջնջել',
    'Error' => 'Սխալ',
    'File upload failed.' => 'Ֆայլի վերբեռնումը ձախողվեց',
    'Home' => 'Գլխավոր էջ',
    'Invalid data received for parameter "{param}".' => 'Անվավեր պարամետր արժեք "{param}".',
    'Login Required' => 'Մուտք պարտադիր է.',
    'Missing required arguments: {params}' => 'Անհայտ պատճառաբանությունները բացակայում են: {params}',
    'Missing required parameters: {params}' => 'ահանջվող պարամետրերը բացակայում են: {params}',
    'No' => 'Ոչ',
    'No results found.' => 'Ոչինչ չի գտնվել.',
    'Only files with these MIME types are allowed: {mimeTypes}.' => 'Միայն այս MIME տեսակի ֆայլերը թույլատրվում են: {mimeTypes}.',
    'Only files with these extensions are allowed: {extensions}.' => 'Միայն թույլատրվում են հետեւյալ ընդարձակման ֆայլերը {extensions}.',
    'Page not found.' => 'Էջը չի գտնվել.',
    'Please fix the following errors:' => 'Խնդրում ենք ամրագրել հետեւյալ սխալները:',
    'Please upload a file.' => 'Խնդրում ենք վերբեռնել ֆայլ:',
    'The combination {values} of {attributes} has already been taken.' => '{values} պարամետրերի համադրությունը {attributes} արդեն գոյություն ունի:',
    'The file "{file}" is not an image.' => '«{file}» ֆայլը պատկերը չէ:',
    'The file "{file}" is too big. Its size cannot exceed {formattedLimit}.' => '"{file}" ֆայլը չափազանց մեծ է: Չափը չպետք է գերազանցի {formattedLimit}:',
    'The file "{file}" is too small. Its size cannot be smaller than {formattedLimit}.' => '«{file}» ֆայլը չափազանց փոքր է: Չափը պետք է լինի ավելի քան {formattedLimit}:',
    'The format of {attribute} is invalid.' => '{attribute} արժեքի ձեւաչափը սխալ է',
    'The requested view "{name}" was not found.' => '«{name}» հայցվող ֆայլը չի գտնվել:',
    'The verification code is incorrect.' => 'Անհայտ հաստատման կոդ:',
    'Unable to verify your data submission.' => 'Չհաջողվեց ստուգել ուղարկված տվյալները:',
    'Unknown alias: -{name}' => 'Անհայտ մականուն: -{name}',
    'Unknown option: --{name}' => 'Անորոշ տարբերակ `- {name}',
    'Update' => 'Խմբագրել',
    'View' => 'Դիտել',
    'Yes' => 'Այո',
    'You are not allowed to perform this action.' => 'Ձեզ չի թույլատրվում կատարել այս գործողությունը:',
    'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.' => 'Դուք չեք կարող վերբեռնել {limit, number} {limit, plural, one{файла} few{файлов} many{файлов} other{файла}}.',
    'just now' => 'հենց հիմա',
    'the input value' => 'մուտքային արժեքը',
    '{attribute} "{value}" has already been taken.' => 'արդեն ձեռնարկվել է »',
    '{attribute} cannot be blank.' => '«{attribute}» չի կարող լինել դատարկ.',
    '{attribute} contains wrong subnet mask.' => '{attribute} պարունակում է սխալ ներքին ցանցի ծածկույթ:',
    '{attribute} is invalid.' => '{attribute} անվավեր է:',
    '{attribute} is not a valid URL.' => '{attribute} վավեր URL չէ:',
    '{attribute} is not a valid email address.' => '{attribute} վավեր էլփոստի հասցեն չէ:',
    '{attribute} is not in the allowed range.' => '{attribute} - ը թույլատրված տիրույթում չէ:',
    '{attribute} must be "{requiredValue}".' => '{attribute}- ը պետք է լինի "{requiredValue}',
    '{attribute} must be a number.' => '{attribute} թիվը պետք է լինի:',
    '{attribute} must be a string.' => '{attribute} - ը պետք է լինի տող:',
    '{attribute} must be a valid IP address.' => '{attribute} - ը պետք է լինի վավեր IP հասցե:',
    '{attribute} must be an IP address with specified subnet.' => '{attribute} - ը պետք է լինի IP հասցե, նշված ենթակետով:',
    '{attribute} must be an integer.' => '{attribute} - ը պետք է լինի ամբողջական:',
    '{attribute} must be either "{true}" or "{false}".' => '{attribute}- ը պետք է լինի «{true}» կամ «{false}»:',
    '{attribute} must be equal to "{compareValueOrAttribute}".' => '{attribute} - ը պետք է լինի հավասար "{compareValueOrAttribute}":',
    '{attribute} must be greater than "{compareValueOrAttribute}".' => '{attribute}- ը պետք է լինի ավելի մեծ, քան "{compareValueOrAttribute}":',
    '{attribute} must be greater than or equal to "{compareValueOrAttribute}".' => '{attribute}- ը պետք է լինի մեծ կամ հավասար "{compareValueOrAttribute}":',
    '{attribute} must be less than "{compareValueOrAttribute}".' => '{attribute}- ը պետք է լինի պակաս, քան "{compareValueOrAttribute}":',
    '{attribute} must be less than or equal to "{compareValueOrAttribute}".' => '{attribute}- ը պետք է լինի պակաս կամ հավասար "{compareValueOrAttribute}":',
    '{attribute} must be no greater than {max}.' => '{attribute} - ը պետք է լինի ոչ ավելի, քան {max}:',
    '{attribute} must be no less than {min}.' => '{attribute} - ը պետք է լինի ոչ պակաս, քան {min}:',
    '{attribute} must not be a subnet.' => '{attribute} - ը չպետք է լինի ենթահամակարգ:',
    '{attribute} must not be an IPv4 address.' => '{attribute}- ը չպետք է լինի IPv4 հասցե:',
    '{attribute} must not be an IPv6 address.' => '{attribute} - ը չպետք է լինի IPv6 հասցե:',
    '{attribute} must not be equal to "{compareValueOrAttribute}".' => '{attribute}- ը չպետք է հավասար լինի «{compareValueOrAttribute}»:',
    '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' => '{attribute}- ը պետք է պարունակի առնվազն {min, number} {min, plural, one {character} այլ {characters}}:',
    '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.' => '{attribute} պարունակությունը պետք է պարունակի {max, number} {max, plural, one {character} այլ {characters}}',
    '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.' => '{attribute}- ը պետք է պարունակի {length, number} {length, plural, one{character} other{characters}}:',
    'Are you sure you want to delete this item?' => 'Վստահ եք, որ ցանկանում եք ջնջել այս տարրը',
];
